#98の解決
winc1980/secure.register.winc.ne.jp pull request #100
Opened 2022-07-28 09:11 UTC by nanami-g

#98に対応しています。
一人前認定試験用のプルリクです。

2022-07-30 01:19 UTC, kanako0424 requested changes
細かくて申し訳ないのですが、92, 98行目のaタグの終了タグのインデントを開始タグと揃えてください!あとはいいと思います！

2022-07-30 09:21 UTC, nanami-g commented
ありがとうございます。
修正しましたので確認よろしくお願いいたします。

2022-07-31 15:42 UTC, kanako0424 approved these changes

2022-07-31 15:42 UTC, merged

2022-07-31 15:43 UTC, kanako0424 commented
一人前課題合格です