fix flow-design
winc1980/secure.register.winc.ne.jp pull request #54
Opened 2022-03-17 07:31 UTC by natsumi-ii

WIP

残り
- 数字小さく
- 間隔狭く
- 数字と文字のスペース広く

2022-03-17 10:21 UTC, kanako0424 requested changes
![image](https://user-images.githubusercontent.com/59760635/158788204-25d71d75-faea-484d-bd0e-70b896426e3f.png)
class="mb-3" はmargin-bottomのことなので 、style属性にmargin-bottomを0にしても、marginは消えてないと思います。

bootstrapのmarginについては以下を参照してね
https://getbootstrap.jp/docs/4.2/utilities/spacing/


bootstrapの解説ドキュメントを作るね！
今日はbootstrapの解説ちゃんとできなくてごめんね。
あと、数字と文字の高さがあっているのはめちゃ良き。

2022-03-17 23:32 UTC, natsumi-ii commented
close #51

bootstrapの解説ドキュメント作っていただけると、とても助かります！

conflictは

2022-03-18 08:39 UTC, kanako0424 commented
bootstrapのdocumentというか最低限の知識は、2020年に使用していたwincの教材を、notionの見習いのところに追加してみたから、みてみてね。
notionのどこをみたらいいかわからない場合は、discordで既になつみちゃんにメンションしていると思うので、確認してみてください〜

2022-03-18 08:39 UTC, kanako0424 approved these changes
LGTM

2022-03-18 08:44 UTC, kanako0424 commented
そういえば、迅速に対応してくれてありがとう。
次の活動の時に直すのでぜんぜん遅くないので、もし早くやらなきゃ！と思っていたら、そう思わなくて大丈夫だよ。

2022-03-18 08:45 UTC, merged

2022-03-18 09:11 UTC, kanako0424 commented
![image](https://user-images.githubusercontent.com/59760635/158973930-1e818960-a0d3-445e-a249-6a743e794f0d.png)

bootstrapにd-flexが用意されているので、style属性に書いてあるものをこれに直させてもらうね。

やっていることは同じです。