[update] 04振り込み金額の表を追加
winc1980/secure.register.winc.ne.jp pull request #56
Opened 2022-03-17 07:34 UTC by manasan-iTL

close #49

2022-03-17 10:13 UTC, kanako0424 requested changes
すごい、tableになっているのはとても良い！
けど、03 振込先の確認 のtableのデザインと同じにすると、ペルソナが「なんで表のデザイン違うんだ？？」って思わずに済むかなと思います。

合計の前が太い線なのは、みやすいです。

2022-03-18 08:21 UTC, manasan-iTL commented
見た目は03の表と同じ感じにしたんですが、表ヘッダーの「振り込み金額について」はいると思いますか？
以下参考画像
①ヘッダーなし
<img width="730" alt="キャプチャ" src="https://user-images.githubusercontent.com/52818097/158962298-04eb3a47-d814-4e28-ac02-61127bfebbdc.PNG">
②ヘッダーあり（一応ヘッダーの文字は中央寄せしてますが、左寄せも可）
<img width="728" alt="キャプチャ2" src="https://user-images.githubusercontent.com/52818097/158963015-4cbf70a4-502e-45d2-8a35-469f622a3b0e.PNG">

2022-03-18 08:28 UTC, kanako0424 commented
ごちゃごちゃするからいらないと思ってる。代わりに、
合計のところを合計振込金額にしたらどうだろう？

2022年3月18日(金) 17:21 manasan-iTL ***@***.***>:

> 見た目は03の表と同じ感じにしたんですが、表ヘッダーの「振り込み金額について」はいると思いますか？
> 以下参考画像
> ①ヘッダーなし
> [image: キャプチャ]
> <https://user-images.githubusercontent.com/52818097/158962298-04eb3a47-d814-4e28-ac02-61127bfebbdc.PNG>
> ②ヘッダーあり（一応ヘッダーの文字は中央寄せしてますが、左寄せも可）
> [image: キャプチャ2]
> <https://user-images.githubusercontent.com/52818097/158963015-4cbf70a4-502e-45d2-8a35-469f622a3b0e.PNG>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/winc1980/secure.register.winc.ne.jp/pull/56#issuecomment-1072141124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOH5764JLD2IJ2XXYXPZZPTVAQ4J5ANCNFSM5Q6DI5UA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you commented.Message ID: <winc1980/secure.
> ***@***.***>
>

2022-03-18 09:09 UTC, manasan-iTL commented
了解です。

2022-03-18 09:17 UTC, manasan-iTL commented
直しました。conflictも解消しておいた方が良いですか？

2022-03-18 10:08 UTC, kanako0424 commented
解消してくれると超助かります！
2022年3月18日(金) 18:17 manasan-iTL ***@***.***>:

> 直しました。conflictも解消しておいた方が良いですか？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/winc1980/secure.register.winc.ne.jp/pull/56#issuecomment-1072222572>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOH57632WB6LGUEFASZCK4TVARC4LANCNFSM5Q6DI5UA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you commented.Message ID: <winc1980/secure.
> ***@***.***>
>

2022-03-18 13:58 UTC, manasan-iTL commented
コンフリクト解消しておきました。

2022-03-18 14:11 UTC, manasan-iTL commented
developの変更に合わせてstyleで指定していた箇所をBootstrapに変えました。

2022-03-18 14:33 UTC, kanako0424 commented
conflict解消して、developの内容を反映してくれるとこんなに楽なのかと感動しています。
本当にありがとう！本当にありがたすぎて今日はいい気分で寝られそうです。

2022-03-18 14:34 UTC, kanako0424 approved these changes
LGTM

2022-03-18 14:34 UTC, merged