Version4
winc1980/secure.register.winc.ne.jp pull request #62
Opened 2022-03-18 09:50 UTC by kanako0424

cssファイルを作成し、style属性で書かれていたものと、cssで書かれていたもののうち、bootstrapで書けるものは、bootstrapに移動しました。

2022-03-18 14:38 UTC, kanako0424 commented
@manasan-iTL 時間がある時に、レビュー試しにやってみてください。
deelpからmasterへのmergeです。今あるpullreqがなくなったので、mergeしちゃおうかなという感じです。
相当変わっているから、変な表示なさそうと思ったらmergeしてみてください。

2022-03-19 02:38 UTC, manasan-iTL requested changes
@kanako0424 
style.cssにレビューを付けておきました。
ただそこまで重要ではないのと、今回のHPはそこまで規模が大きくないので今の状態でも全然大丈夫かなとも思っています。どっちの方が良いと思いますか？

2022-03-19 02:38 UTC, manasan-iTL commented on style.css
> +.faq div:hover {
`.faq div:hover`でも良いと思うけれど、ホバーしているdivに直接クラスを当ててあげたほうが良いかもしれない。
理由
・他のところでホバーを実装するときに使いまわせる
・今の状態だとHTML側(index側)からhoverしたときの挙動が分かりづらい
　クラス名を`onhover`みたいにしたらHTML見たときに分かりやすい

2022-03-19 04:05 UTC, kanako0424 commented on style.css
> +.faq div:hover {
ありがとう、そうするわ！onhoverにして、コンポーネント化しよう。

2022-03-19 04:09 UTC, kanako0424 commented
クラスにhoverと単語を入れた他だけで、他の要素にも使いまわせるようになったので、確認お願いします。

2022-03-19 07:10 UTC, manasan-iTL approved these changes
確認しました。

2022-03-19 07:11 UTC, merged

2022-03-19 07:12 UTC, manasan-iTL commented
メインブランチにマージしました。